language: go
go:
    - 1.4

script:
    - go test -cover ./...

install:
    - go get github.com/facebookgo/ensure github.com/mattn/go-sqlite3 github.com/DATA-DOG/go-sqlmock github.com/landjur/go-uuid golang.org/x/crypto/bcrypt

notifications:
    email:
        on_success: change
        on_failure: always

addons:
    hosts:
        - localhost