language: go
go:
    - 1.4

install:
    - go get github.com/dkulchenko/bunch
    - bunch install

script:
    - bunch go build
    - bunch go test -cover ./... -race

notifications:
    email:
        on_success: change
        on_failure: always

addons:
    hosts:
        - localhost