storage:
    provider: sqlite
    sqlite:
        dbpath: geilmail.db
imap:
    listenip: 0.0.0.0
    port: 1143
smtp:
    listenip: 0.0.0.0
    port: 1587
tls:
    certpath: ""
    keypath: ""
http:
    listen: 0.0.0.0:51488
